Downgrade Beautiful soup from 4.8.0
Because of:
> ERROR: wagtail 2.6 has requirement beautifulsoup4<4.6.1,>=4.5.1, but you'll have beautifulsoup4 4.8.0 which is incompatible.

Was 4.6.0 originally, going with 4.6.1 instead